# permissions for end users to edit contours.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contour-editor-role
rules:
- apiGroups:
  - operator.projectcontour.io
  resources:
  - contours
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.projectcontour.io
  resources:
  - contours/status
  verbs:
  - get
